apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  groups:
    - name: application-alerts
      interval: 30s
      rules:
        # Alert when CPU usage exceeds 50%
        - alert: HighCPUUsage
          expr: |
            sum(rate(container_cpu_usage_seconds_total{namespace!="kube-system"}[5m])) by (pod, namespace) > 0.5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has CPU usage above 50% for more than 2 minutes"
        
        # Alert when Pod is not ready
        - alert: PodNotReady
          expr: |
            kube_pod_status_phase{phase!="Running",phase!="Succeeded"} == 1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod is not ready"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in {{ $labels.phase }} state for more than 5 minutes"